Improved Authentication Logic
CrossWars/crosswars pull request #70
Opened 2022-01-02 03:19 UTC by RobertWetzler

Big PR, here's what's mainly changed:

Frontend:
- Navigation gaurds: checks if the user is logged in before allowing them to load pages that require authentication. The authenticated routes are defined in /crosswars-frontend/src/routes.js and the navigation logic is in index.js in the same directory.
- Navigation gaurds will, if user not authenticated/has expired JWT, take the user to the login page, which will then afterwards direct them to the page they were trying to get to previously (by passing nextUrl router query)
- Improved login button to look like a legit login with google button
- Login button checks if user exists and if not makes a POST request

Backend: 
- Auth'd GET user endpoints now don't require passing in a user_id. If user_id not passed, it will return the User of the JWT token. This is useful for getting the current user on the frontend upon login.
- POST a new user now uses a a different Authenticated annotation, because the original one was trying to map the JWT to a user in the database (which will never work for creating new users). Instead, the annotation @AuthenticatedNewUser just makes auth_user a new User  using the JWT data, and then stores in in the database

2022-01-06 04:50 UTC, loomisdf requested changes

2022-01-06 04:50 UTC, loomisdf commented on crosswars-backend/src/main/kotlin/xyz/crosswars/service/GoogleAuthService.kt
> +                User(userId = userId, name=givenName, email=email, remind=false)
why not simplify this section and remove the single use variables
```Kotlin
val payload: GoogleIdToken.Payload = googleIdToken.payload
User(
    userId = payload.subject, 
    name = payload["given_name"] as String, 
    email = payload.email, 
    remind = false
)
```

2022-01-06 04:50 UTC, loomisdf commented on crosswars-frontend/src/pages/GroupPage.vue
> +        return `${location.host}/#/groupInvite/${this.group.id}`
Did it not like the underscores?

2022-01-06 04:50 UTC, loomisdf commented
Other than the one suggestion I made, everything looks good.

2022-01-08 01:23 UTC, loomisdf approved these changes

2022-01-08 03:16 UTC, RobertWetzler commented
Authorized getGroupsByUser, otherwise it would be pretty easy for someone to fingerprint every group a given user is in, and then construct group invite links for each group. As a convention, retrieving a given group's ID should require authorization, so you can only get IDs of the groups you belong to.

2022-01-08 03:18 UTC, RobertWetzler commented
Also with a previous commit - group IDs are now generated randomly, instead of being derived from the group name. That way you can't construct a group invite link just from knowing a group's name

2022-01-08 03:19 UTC, RobertWetzler commented
Also with other previous commit - limited users to only creating 5 groups, otherwise user's could spam group creations and overwhelm the backend

2022-01-10 21:57 UTC, merged